github-ci: port send-telegram-notify to python3
For now python3 is used as the default python on all OS and it is
needed to enable it in send-telegram-notify action.

Found issue [1]:

  Traceback (most recent call last):
    File "<string>", line 3, in <module>
  AttributeError: module 'urllib' has no attribute 'quote_plus'

In Python 3 quote_plus included into urllib.parse.

Check documentaion [2]:

  Note The urllib module has been split into parts and renamed in Python 3 to urllib.request, urllib.parse, and urllib.error.

Check the same issue [3].

This patch changes 'urllib.quote_plus' to 'urllib.parse.quote_plus'.

Closes tarantool/tarantool-qa#112

[1]: https://github.com/tarantool/tarantool/runs/2307719609?check_suite_focus=true#step:5:252
[2]: https://docs.python.org/2/library/urllib.html
[3]: https://github.com/web2py/web2py/issues/1822